### ISSUE TITLE
the PDF generation is reported as failing on ReadTheDocs

### ISSUE THREAD

**Issue by stof** [Behat/docs#10]
See https://readthedocs.org/builds/behat/1368035/ for the logs

**Comment by clemens-tolboom** [comment]
This seems to work agains https://media.readthedocs.org/pdf/behat/v3.0/behat.pdf give one.

**Comment by stof** [comment]
Well, it is still reported as failing, which is weird if the PDF is there: https://readthedocs.org/builds/behat/1577839/

**Comment by clemens-tolboom** [comment]
It wrote the pdf and reports a fail based on exit code 1 ... doh

> ! Package inputenc Error: Unicode char \u8:└ not set up for use with LaTeX.

There are tex error so what code drives sphinx and how does it decides for errors based on output?

**Comment by everzet** [comment]
I disabled the PDF generation for now.
