### ISSUE TITLE
Possible grammar correction: change "got" to "get" in quick_start.rst

### ISSUE THREAD

**Issue by seanbuscay** [Behat/docs#111]
Hello.  Thank you for the continually excellent documentation. 

Should line 269 in the Quick Start documentation read: 

> Finally, we get to the automation part.

Rather than: 

> Finally, we got to the automation part.

Ref: 

https://github.com/Behat/docs/blame/v3.0/quick_start.rst#L269

If it was not an intentional use of the word "got", I can submit a pull request to change it, if you'd like.

**Comment by bocharsky-bw** [comment]
I think it was an intentional use. It means we just did it, i.e. finally, got to the something. Probably, it can be replaced with:

> Finally, we have gotten to the automation part.

**Comment by seanbuscay** [comment]
Hi @bocharsky-bw .  I just referenced [this link](http://www.quickanddirtytips.com/education/grammar/got-proper-english) and it turns out that both forms are proper grammar.  "Got" being more a British english convention.  So I'll close this ticket.  Best Regards.
