### ISSUE TITLE
Definitions Browsing

### ISSUE THREAD

**Issue by gquemener** [Behat/docs#12]
Hello there,

I'd like to drop a suggestion on definition browsing usage with the command line.
I'm always forgetting how to use the `-d` argument of the `behat` command.

How would you like to have a chapter/section/note about that on the documentation (I don't know if this usage has changed with v3?)?

I could even manage to do it.

**Comment by everzet** [comment]
@gquemener is in TODO :)

**Comment by everzet** [comment]
@gquemener if you still can manage to add it - please add it :) New docs are up.

**Comment by gquemener** [comment]
Indeed, this has been dropped from my todo list!
I'm starting it.

**Comment by gquemener** [comment]
PR is here: https://github.com/Behat/docs/pull/39
