### ISSUE TITLE
HTTPS is not valid on website 

### ISSUE THREAD

**Issue by alexisLefebvre** [Behat/docs#122]
That's not related to the code but the website is not accessible through HTTPS:

https://behat.org/en/latest/

I discovered it while changing some links from HTTP from HTTPS. You may have never promoted the https://behat.org/ but having a error is surprising though.

Here is the report from Firefox:

> behat.org uses an invalid security certificate.
> 
> The certificate is only valid for the following names:
> *.readthedocs.org, readthedocs.org
>
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by alexisLefebvre** [comment]
There is the same error on https://mink.behat.org/en/latest/

Browsers  (e.g. [Chrome](https://www.theverge.com/2018/2/8/16991254/chrome-not-secure-marked-http-encryption-ssl)) will soon display errors about sites that don't provide HTTPS access, so it will be a problem in the future.

**Comment by bocharsky-bw** [comment]
Hm, why it was closed?

**Comment by alexisLefebvre** [comment]
https://behat.org/ works today.

http://mink.behat.org works without HTTPS
