### ISSUE TITLE
Missing quotes in suites path code example

### ISSUE THREAD

**Issue by dumitriucristian** [Behat/docs#135]
In this documentation page https://behat.org/en/latest/user_guide/configuration/suites.html#suite-paths, sais that suites path should be declared as:
```
 - %paths.base%/features
```
but this will throw the following error :
```

The reserved indicator "%" cannot start a plain scalar; you need to quote the scalar at line 9 (near "- %paths.base%/features/register").

```
 Quotes should be used, like this:
```
- "%paths.base%/features"
```

I used Symfony5 with Friends-of-Behat

**Comment by pamil** [comment]
Could you open a PR with this change?

**Comment by dumitriucristian** [comment]
done: https://github.com/Behat/docs/pull/136
