### ISSUE TITLE
Update the documentation about Symfony integration and add Laravel integration

### ISSUE THREAD

**Issue by carlos-granados** [Behat/docs#158]
The cookbook that describes the Symfony integration is very outdated, it uses the `behat/symfony2-extension` extension which was archived a long time ago and only supports up to Symfony 4. It should be updated to use the new `friends-of-behat/symfony-extension` extension.

But I wonder if it is worth to have a full cookbook about this integration or if it would be enough to point the users towards the documentation for this extension instead of repeating it all here

We should also point the users towards the documentation of the `laracasts/behat-laravel-extension` which provides similar capabilities for Laravel

**Comment by ttomdewit** [comment]
I'd personally argue that if their docs are succinct that we point there rather than owning the cookbook, as we do not control when things change on their end?

**Comment by carlos-granados** [comment]
> I'd personally argue that if their docs are succinct that we point there rather than owning the cookbook, as we do not control when things change on their end?

That was my thinking as well

**Comment by acoulton** [comment]
Agreed

**Comment by carlos-granados** [comment]
Fixed via https://github.com/Behat/docs/pull/169
