### ISSUE TITLE
Add a GitHub action that builds the site

### ISSUE THREAD

**Issue by carlos-granados** [Behat/docs#160]
Recently we merged a pull request which made the site build fail because it contained a couple of small errors. We should probably add a GitHub action that builds the site and does a quick smoke test before we merge any PR

**Comment by stof** [comment]
I was about to open an issue suggesting the same

**Comment by acoulton** [comment]
That would be a good quick fix until @everzet can re-sync the github webhook to finish #129 which will get the PR builds (and commit statuses) working with RtD.
