### ISSUE TITLE
Provide more information about Mink

### ISSUE THREAD

**Issue by carlos-granados** [Behat/docs#165]
In our current docs Mink is barely mentioned in passing in a couple of places. But Mink is for most users a fundamental piece of functionality that allows them to use Behat to its full capacity. I think we should provide a more detailed explanation of what Mink is and a summary of how it can be used with Behat, pointing the users to the Mink repo and docs for more information

**Comment by stof** [comment]
Given that the MinkExtension has been moved to FriendsOfBehat (keeping the Behat organization focused on the core of Behat), does this belong to the Behat documentation itself or in the documentation of the extension (which is clearly lacking right now, as the readme does not even link to it right now) ?

And for usage of the Mink APIs inside custom steps, the MinkExtension should ideally avoid duplicating the Mink documentation (contributions are welcome in https://github.com/minkphp/docs/ to improve the Mink documentation of course)

**Comment by carlos-granados** [comment]
@stof the core of the documentation for Mink belongs in the Mink and Mink extension docs, of course, but the Behat documentation should at least clearly highlight the existence of Mink and its extension with an overview of what you can achieve with it. Right now it mostly assumes that you know what Mink is but for any user who is new to Behat they may have no idea and may miss this important part of the equation
