### ISSUE TITLE
Content checks

### ISSUE THREAD

**Issue by szepeviktor** [Behat/docs#174]
Please consider running sphinx-lint and typos.

https://github.com/szepeviktor/byte-level-care/blob/master/.github/workflows/sphinx.yml#L28
https://github.com/szepeviktor/byte-level-care/blob/master/.github/workflows/spelling.yml#L33

**Comment by acoulton** [comment]
Thanks for the suggestion @szepeviktor - I'm not familiar with those tools (I don't think any of the new/active maintainers are particularly familiar with sphinx & python) but it looks like it could be helpful. If you'd like to propose a PR we'll consider it, that is probably the quickest way to get this looked at.

**Comment by stof** [comment]
Another tool that can be used is [doctor-rst](https://github.com/OskarStark/doctor-rst), which is used by the Symfony documentation for instance
