### ISSUE TITLE
Dead Link on https://github.com/Behat/docs/blob/master/guides/1.gherkin.rst

### ISSUE THREAD

**Issue by ghost** [Behat/docs#18]
On the "steps" section 
"Robert C. Martin has written a great post about BDD's Given-When-Then concept where he thinks of them as a finite state machine."

There is linking to the post but the link is dead, please fix it if you could find the correct link anywhere, I did find some but not sure if they are the correct one.

https://sites.google.com/site/unclebobconsultingllc/the-truth-about-bdd

**Comment by everzet** [comment]
Could you send a PR?

**Comment by gquemener** [comment]
This is closable now
