### ISSUE TITLE
Different variable

### ISSUE THREAD

**Issue by ghost** [Behat/docs#19]
On this part https://github.com/Behat/docs/blob/master/guides/1.gherkin.rst#tables example has 

``` php
/**
 * @Given the following people exist:
 */
public function thePeopleExist(TableNode $table)
{
    foreach ($hash as $row) {
        // $row['name'], $row['email'], $row['phone']
    }
}
```

shouldnt that $hash be $table ?

**Comment by everzet** [comment]
Could you send a PR?

**Comment by ghost** [comment]
I will try to send, but I am not familiar with the mark down :(

**Comment by stof** [comment]
well, renaming the variable in the code snippet does not require a huge knowledge of the rST syntax (it is not Markdown btw)
