### ISSUE TITLE
Syntax issue

### ISSUE THREAD

**Issue by ghost** [Behat/docs#20]
https://github.com/Behat/docs/blob/master/guides/2.definitions.rst#definitions-home---featurecontext-class

"Step definitions are just normal PHP methods. They are instance methods in a special class called Feature:doc:Context</guides/4.contexts>. This class can be easily created by running behat with the --init command from your project's directory:"

Link was not properly created.

**Comment by stof** [comment]
This is because the rST rendering on github is incomplete (it renders files in isolation). the doc is meant to be rendered using Sphinx. Use the doc rendered on ReadTheDocs (by following the link in the readme of Behat or in the description of the repo)

**Comment by ghost** [comment]
I found the issue from the Read the docs page, http://behat.readthedocs.org/en/latest/guides/2.definitions.html

**Comment by stof** [comment]
ah indeed, I looked at the wrong link. This is now fixed

**Comment by ghost** [comment]
Thanks :)
