### ISSUE TITLE
Some notes on site

### ISSUE THREAD

**Issue by clemens-tolboom** [Behat/docs#23]
To start with: http://behat.readthedocs.org/en/latest/index.html looks way better then the http://behat.org/
- [x] Is this docs repo for replacing http://behat.org/ pages? Maybe add a readme here and a XRef on http://behat.org/ for now?
- [x] Align site to center. On wide screen it's hard to read all text. Or has that to do with https://readthedocs.org/ ?

Thanks and I will continu reading :p

**Comment by stof** [comment]
We have plans to replace the current behat.org website (which currently talks about Behat 2.5). But this is not ready yet. Adding a link to behat.org which describes the old Behat version while this doc is for the new version would be confusing IMO.

the theme has to do with ReadTheDocs.

**Comment by clemens-tolboom** [comment]
It would have saved us some hours digging dirt.

What about

> For using Behat 3 see the work in progress on http://behat.readthedocs.org which will replace the content on http://behat.org in the near future.

and

> For using the older version Behat 2 see the http://behat.org

**Comment by stof** [comment]
Well, the Behat readme already links to the Beha 3 doc

**Comment by clemens-tolboom** [comment]
I meant something like this :)

![behat__bdd_for_php](https://cloud.githubusercontent.com/assets/371014/3429398/b0989b64-0053-11e4-893b-3b0b5556c1c1.png)

**Comment by everzet** [comment]
New docs are up

**Comment by clemens-tolboom** [comment]
Thanks for the align center.

But is it better then before? I really liked the sidebar :(

But the PDF is fixed :+1:
