### ISSUE TITLE
Broken layout on Gherkin page

### ISSUE THREAD

**Issue by aik099** [Behat/docs#25]
URL: http://behat.readthedocs.org/en/latest/guides/1.gherkin.html#givens
![behatgherkinreadthedocsbug](https://cloud.githubusercontent.com/assets/1277526/3480717/11a90948-0365-11e4-8ca4-484dff620db0.png)

**Comment by stof** [comment]
see #17

**Comment by aik099** [comment]
Great, I with that PR can be merged then.
