### ISSUE TITLE
Mink with v3 cookbook article

### ISSUE THREAD

**Issue by everzet** [Behat/docs#29]

**Comment by stof** [comment]
well, what we need is rendering the extension doc online again. The rST doc of the MinkExtension is uptodate for v3 in the extension repo (we might want to extend it later though)

**Comment by everzet** [comment]
@stof `MinkExtension` doc will come to behat.org, but it is essentially an information on basics of how to configure and use MinkExtension. Where's I'm thinking about actual article on how to drive web application development with Mink and MinkExtension. More high level example of the process

**Comment by stof** [comment]
@everzet but should this live in the Behat doc repo or should we rather enhance the extension doc by having multiple pages in it ?

**Comment by everzet** [comment]
@stof that's a very good point actually :)

**Comment by stof** [comment]
this means we need to decide how extensions doc will be rendered on behat.org (which may be hard if we continue to rely on ReadTheDocs for the website) and then we will update the MinkExtension doc to add more pages based on the convention

**Comment by everzet** [comment]
@stof we can't use RTD for extensions docs. And I'm thinking about ditching it for docs.behat.org too in the process. RTD is the MVP :)

**Comment by stof** [comment]
Does this mean that the new website has seen some progress ?
