### ISSUE TITLE
Doc still says to install behat 2.4 and mink 1.4

### ISSUE THREAD

**Issue by ari-gold** [Behat/docs#90]
http://docs.behat.org/en/v2.5/cookbook/behat_and_mink.html

```
  "behat/behat": "2.4.*@stable",
  "behat/mink": "1.4.*@stable",
```

Is that still the recommendation?

**Comment by stof** [comment]
no it is not. I updated the installation chapter a long time ago, but I forgot that the Mink cookbook was also showing installation steps. the doc has been updated now.

**Comment by cauerego** [comment]
I couldn't find in [composer docs](https://getcomposer.org/doc/01-basic-usage.md), but insisting a bit more [found more about it](http://qpleple.com/understand-composer-versions/)! :)

But [it looks like Behat 3 works with Mink just fine](http://stackoverflow.com/questions/25049234/mink-doesnt-work-with-behat-3-0-12). Why setting it to the older version?

**Comment by stof** [comment]
@cauerego because this is the doc for Behat 2.5 (see the URL). The doc for Behat 3.0 are showing how to install 3.0

**Comment by cauerego** [comment]
D'oh!
